# ==============================================================================
# ⭐ ПОДДЕРЖКА ПРОЕКТА ЗВЕЗДОЙ НА GITHUB (STAR REPOSITORY) ⭐
#
# Самый простой, ценный и бесплатный способ поддержать развитие TMA Builder —
# поставить ЗВЕЗДУ (⭐️ Star) этому репозиторию на GitHub!
#
# 👉 Репозиторий: https://github.com/blesswrld/tma-builder
# 👉 Просто нажмите кнопку «Star ⭐️» в правом верхнем углу страницы репозитория!
#
# Каждая звезда помогает проекту расти, привлекать новых пользователей,
# разработчиков и мотивирует автора регулярно выпускать новые релизы! Спасибо! ❤️
# ==============================================================================

# Официальный профиль автора для спонсорства на GitHub
github: [blesswrld] # https://github.com/sponsors/blesswrld

# Пользовательские ссылки для связи и прямой поддержки (Telegram и др., до 4 ссылок)
custom: ['https://t.me/tamerlan_webdev']

